### ISSUE TITLE
Add the ability for a user to mark themself as a GM in the campaign sheet

### ISSUE THREAD

**Issue by scottbenton** [scottbenton/Iron-Fellowship#4]
Add a new optional database variable to the campaign database, `gmId`. 

If the `gmId` is not set, we need to add another button on the CampaignSheetPage for a user to mark themselves as a GM.

If a GM id is set, and the current user is the GM, we should give them the ability to delete the campaign, or remove themselves as the GM. 

If the GM leaves the campaign, the `gmId` should be unset.

**Comment by cptleo92** [comment]
Thinking of doing something like this: 

![image](https://user-images.githubusercontent.com/96504457/216847228-0bf1b5b7-c25f-46ff-8f54-4a74bfe22517.png)

Of course if there is a GM, it'll display something different, maybe the user info for everyone to see. 

If the current user is the GM, maybe add some buttons on the right of the section heading, like in the sections below. 

![image](https://user-images.githubusercontent.com/96504457/216847443-c6e4fce1-7635-43e2-8c3e-a0be7225d8ac.png)

Let me know your thoughts! And what text you'd want in there.

**Comment by scottbenton** [comment]
Hey, sorry! I don't know why I don't get notified of these comments. Would you mind tagging me in the future - if it notifies me I might be able to respond quicker. I like the look of it! 

I don't think we currently have a way to get another user's info from firebase, so we might want to create a new collection in Firestore for users to store their display name and photoUrl. Whenever a user logs in, we could set their entry in that collection with the most recent data. 

Once we have that in place though, we can store the GM's id, and then make a separate call to fetch their profile and display it on that page. Perhaps in the future we display everyone in the campaign somewhere there as well.

**Comment by scottbenton** [comment]
Let me know if you want clarification or need a hand on anything!

**Comment by cptleo92** [comment]
I'll be sure to tag you next time on a fresh issue. This one might actually notify you from now on... let's find out. 

I've never actually used Firebase before but I'm slowly figuring out how it works. Within the `loginWithGoogle()` function, I can pull the data I need and use setDoc, filling out the users collection like so:
``` js
[uid]: {
    displayName: 'name',
    photoURL: 'https: etc etc'
}
```
I added this to the Firestore rules as well, in both the `firestore.rules` file and on the console. 
```
   match /users/{userId} {
    	allow read: if true;
    	allow write: if userId == request.auth.uid;
    }
```

Not sure if I missed anything, but so far it seems to be working. Main concern is how Firestore rules works, and if this needs to be addressed in your state management as well.

**Comment by scottbenton** [comment]
Looks great so far! I might implement an auth provider other than Google at some point, so I'd probably move the user update call to an "onAuthStateChanged" function. I implement one somewhere that you could hook into.
